NS_SUBDOMAIN=""
TUNNEL_SUBDOMAIN=""
NS_DOMAIN="fr.freefrnet.space"
TUNNEL_DOMAIN="fr.freefrnet.space"
PUBLIC_KEY="e7409727dde29dbeaf628afbb2a87d1f741f6b706d602f3a81214d57cfe0ff4b"
FORWARD_DESC="SSH (port 22)"
DNSTT_RECORDS_MANAGED="false"
HAS_IPV6="false"
MTU_VALUE=""
